apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doppler-kubernetes-operator
  namespace: doppler-kubernetes-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pangarabbit
  source:
    repoURL: "https://helm.doppler.com"
    targetRevision: 1.5.1
    chart: doppler-kubernetes-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: doppler-kubernetes-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
